name: TypeScript Action
author: Austen Stone
description: A TypeScript Action
branding:
  icon: "plus"
  color: "blue"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  content-type:
    description: Content to output. json or csv.
    default: json
    required: false
  owner:
    description: The owner of the repository
    default: ${{ github.event.repository.owner.login }}
    required: false
  repo:
    description: The name of the repository
    default: ${{ github.event.repository.name }}
    required: false

outputs:
  data:
    description: The data output from the action
runs:
  using: "node16"
  main: "dist/index.js"
