name: Pi Chart
on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  pi-chart-job-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/label-stats@main
        id: labels
      - uses: actions/github-script@v6
        with:
          script: |
            const data = Object.entries(JSON.parse(`${{ steps.labels.outputs.data }}`));
            await core.summary
              .addRaw(data.slice(0, 20).reduce((acc, [key, value]) =>
              acc + `\n    "${key}" : ${value}`,
              `\`\`\`mermaid
              pie showData
                title Label Usage`
            ) + '\n```', true)
              .addTable([
                [{data: 'Label', header: true}, {data: 'Usage', header: true}],
                ...data.reduce((acc, [key, value]) => {
                  acc.push([key, JSON.stringify(value)]);
                  return acc;
                }, [])
              ])
              .write();
