name: Pi Chart
on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  pi-chart-job-summary:
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/label-stats@main
        id: labels
      - uses: actions/github-script@v6
        with:
          script: |
            const data = Object.entries(JSON.parse(`${{ steps.labels.outputs.data }}`));
            const other = data.slice(19)?.reduce((total, [key, value]) => total + value, 0);
            const raw = data.slice(0, 19).reduce((acc, [key, value]) =>
              acc + `\n    "${key}" : ${value}`,
              `\`\`\`mermaid
            pie showData
            title Label Usage`)
              + (other ? `\n    "other" : ${other}` : '') + '\n```';
            const table = [
              [{ data: 'Label', header: true }, { data: 'Usage', header: true }],
              ...data.reduce((acc, [key, value]) => {
                acc.push([key, JSON.stringify(value)]);
                return acc;
              }, [])
            ];
            await core.summary
              .addRaw(raw, true)
              .addTable(table)
              .write();